# Form implementation generated from reading ui file 'internal/ooi/aooth.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 709)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color:rgb(77,34,14);\n"
"background-color: rgb(77,34,14);\n"
"background-color: rgb(80,200,120);\n"
"background-color: rgb(89,53,31);")
        self.centralwidget.setObjectName("centralwidget")
        self.form_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.form_widget.setGeometry(QtCore.QRect(130, 130, 691, 461))
        self.form_widget.setStyleSheet("background-color: rgb(33, 100, 43);\n"
"border-radius: 25px;")
        self.form_widget.setObjectName("form_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.form_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 671, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.form_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.form_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.form_layout.setContentsMargins(0, 0, 0, 0)
        self.form_layout.setSpacing(10)
        self.form_layout.setObjectName("form_layout")
        self.lbls_layout = QtWidgets.QVBoxLayout()
        self.lbls_layout.setObjectName("lbls_layout")
        self.lbl_username = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lbl_username.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_username.sizePolicy().hasHeightForWidth())
        self.lbl_username.setSizePolicy(sizePolicy)
        self.lbl_username.setMinimumSize(QtCore.QSize(300, 30))
        self.lbl_username.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lbl_username.setToolTipDuration(-1)
        self.lbl_username.setAutoFillBackground(False)
        self.lbl_username.setStyleSheet("background-color: rgb(168,228,160);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 4px;\n"
"border: 1px solid black;\n"
"")
        self.lbl_username.setInputMask("")
        self.lbl_username.setText("")
        self.lbl_username.setMaxLength(50)
        self.lbl_username.setFrame(True)
        self.lbl_username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_username.setClearButtonEnabled(False)
        self.lbl_username.setObjectName("lbl_username")
        self.lbls_layout.addWidget(self.lbl_username, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_psw = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lbl_psw.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_psw.sizePolicy().hasHeightForWidth())
        self.lbl_psw.setSizePolicy(sizePolicy)
        self.lbl_psw.setMinimumSize(QtCore.QSize(300, 30))
        self.lbl_psw.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lbl_psw.setToolTipDuration(-1)
        self.lbl_psw.setAutoFillBackground(False)
        self.lbl_psw.setStyleSheet("background-color: rgb(168,228,160);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 4px;\n"
"border: 1px solid black;\n"
"")
        self.lbl_psw.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.lbl_psw.setInputMask("")
        self.lbl_psw.setText("")
        self.lbl_psw.setMaxLength(100)
        self.lbl_psw.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lbl_psw.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_psw.setClearButtonEnabled(False)
        self.lbl_psw.setObjectName("lbl_psw")
        self.lbls_layout.addWidget(self.lbl_psw, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.form_layout.addLayout(self.lbls_layout)
        self.btns_layout = QtWidgets.QHBoxLayout()
        self.btns_layout.setObjectName("btns_layout")
        self.btn_login = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_login.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 153))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46, 140))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 153))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 153))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46, 140))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 75, 46, 140))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.btn_login.setPalette(palette)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btn_login.setStyleSheet("QPushButton {\n"
"    background-color: rgb( 168,228,160);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 4px;\n"
"    border: 1px solid black;\n"
"    height: 30px;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: rgb(168,228,160);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(168,228,160, 0.55);\n"
"    color: rgba(0, 0, 0, 0.6);\n"
"}\n"
"")
        self.btn_login.setFlat(True)
        self.btn_login.setObjectName("btn_login")
        self.btns_layout.addWidget(self.btn_login)
        self.btn_signup = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_signup.setEnabled(False)
        self.btn_signup.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btn_signup.setStyleSheet("QPushButton {\n"
"    background-color: rgb(168,228,160);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 4px;\n"
"    border: 1px solid black;\n"
"    height: 30px;\n"
"}\n"
"QPushButton:pressed {\n"
"  background-color: rgb(168,228,180);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(168,228,160, 0.55);\n"
"    color: rgba(0, 0, 0, 0.6);\n"
"}")
        self.btn_signup.setObjectName("btn_signup")
        self.btns_layout.addWidget(self.btn_signup)
        self.form_layout.addLayout(self.btns_layout)
        self.form_widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.form_widget_2.setGeometry(QtCore.QRect(125, 125, 701, 471))
        self.form_widget_2.setStyleSheet("background-color: rgb(168,228,160);\n"
"border-radius: 25px;")
        self.form_widget_2.setObjectName("form_widget_2")
        self.form_widget_2.raise_()
        self.form_widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_username.setPlaceholderText(_translate("MainWindow", "Введите имя"))
        self.lbl_psw.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.btn_login.setText(_translate("MainWindow", "Войти в аккаунт"))
        self.btn_signup.setText(_translate("MainWindow", "Создать аккаунт"))
