# Form implementation generated from reading ui file 'internal/ooi/aoothors.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(324, 234)
        about.setStyleSheet("background-color: rgb(1, 67, 30);")
        self.text_wdt = QtWidgets.QTextEdit(parent=about)
        self.text_wdt.setGeometry(QtCore.QRect(30, 10, 271, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.text_wdt.setFont(font)
        self.text_wdt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.text_wdt.setStyleSheet("color: rgb(243, 198, 32);")
        self.text_wdt.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.text_wdt.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.text_wdt.setLineWidth(0)
        self.text_wdt.setReadOnly(True)
        self.text_wdt.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.text_wdt.setObjectName("text_wdt")

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "Form"))
        self.text_wdt.setHtml(_translate("about", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Проект подготовили:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Ткаченко Тихон</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Войт Эвелина</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Рабаданов Далгат</span></p></body></html>"))
