# Form implementation generated from reading ui file 'internal/ooi/leedeerbhoord.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_records(object):
    def setupUi(self, records):
        records.setObjectName("records")
        records.resize(619, 734)
        records.setStyleSheet("background-color: rgb(1, 67, 30);")
        self.centralwidget = QtWidgets.QWidget(parent=records)
        self.centralwidget.setObjectName("centralwidget")
        self.records_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.records_label.setGeometry(QtCore.QRect(130, 70, 351, 61))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.records_label.setFont(font)
        self.records_label.setStyleSheet("color: rgb(243, 198, 32);")
        self.records_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.records_label.setObjectName("records_label")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(130, 150, 351, 431))
        self.tableWidget.setStyleSheet("color: rgb(243, 198, 32);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        records.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=records)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 26))
        self.menubar.setObjectName("menubar")
        records.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=records)
        self.statusbar.setObjectName("statusbar")
        records.setStatusBar(self.statusbar)

        self.retranslateUi(records)
        QtCore.QMetaObject.connectSlotsByName(records)

    def retranslateUi(self, records):
        _translate = QtCore.QCoreApplication.translate
        records.setWindowTitle(_translate("records", "MainWindow"))
        self.records_label.setText(_translate("records", "Таблица рекордов"))
