# Form implementation generated from reading ui file 'internal/ooi/meenyoo.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Blackjack(object):
    def setupUi(self, Blackjack):
        Blackjack.setObjectName("Blackjack")
        Blackjack.resize(521, 645)
        Blackjack.setStyleSheet("background-color: rgb(0, 76, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=Blackjack)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.MainLabel.setGeometry(QtCore.QRect(100, 10, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Cond")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.MainLabel.setFont(font)
        self.MainLabel.setStyleSheet("background-color: rgb(0, 77, 0);\n"
"border-top-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0)")
        self.MainLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MainLabel.setObjectName("MainLabel")
        self.Begin_game = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Begin_game.setGeometry(QtCore.QRect(30, 370, 201, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Begin_game.setFont(font)
        self.Begin_game.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Begin_game.setObjectName("Begin_game")
        self.Records = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Records.setGeometry(QtCore.QRect(130, 470, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Records.setFont(font)
        self.Records.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.Records.setObjectName("Records")
        self.Settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Settings.setGeometry(QtCore.QRect(250, 370, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Settings.setFont(font)
        self.Settings.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Settings.setText("О программе")
        self.Settings.setObjectName("Settings")
        self.Photo = QtWidgets.QLabel(parent=self.centralwidget)
        self.Photo.setGeometry(QtCore.QRect(110, 80, 281, 171))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("internal/ooi\\images (1).jpg"))
        self.Photo.setObjectName("Photo")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 550, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        Blackjack.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Blackjack)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 26))
        self.menubar.setObjectName("menubar")
        Blackjack.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Blackjack)
        self.statusbar.setObjectName("statusbar")
        Blackjack.setStatusBar(self.statusbar)

        self.retranslateUi(Blackjack)
        QtCore.QMetaObject.connectSlotsByName(Blackjack)

    def retranslateUi(self, Blackjack):
        _translate = QtCore.QCoreApplication.translate
        Blackjack.setWindowTitle(_translate("Blackjack", "MainWindow"))
        Blackjack.setWhatsThis(_translate("Blackjack", "<html><head/><body><p><img src=\"https://www.liveabout.com/thmb/_CkaBejGkMkOZl2fs1uwslQrOVk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/winning-blackjack-hand-on-casino-table-520257696-58979c263df78caebc19a6e7.jpg\"/></p></body></html>"))
        self.MainLabel.setText(_translate("Blackjack", "   ДОБРО ПОЖАЛОВАТЬ!"))
        self.Begin_game.setText(_translate("Blackjack", " Начать игру"))
        self.Records.setText(_translate("Blackjack", "Таблица рекордов"))
        self.pushButton.setText(_translate("Blackjack", "Правила"))
